### ISSUE TITLE
Problem with file-names

### ISSUE THREAD

**Issue by evdbij** [modxcms/imageSlim#2]
I started testing imageSlim and I had a small problem. It seems like imageSlim ignores a part of my filename. I have three files (p.e. image-1.png, image-2.png, image-3.png). imageSlim seems to ignore the '-#' part en outputs the first image three times

**Comment by oo12** [comment]
Yes, I discovered that a few days ago too.  The problem is actually caused by a [bug in phpThumbOf](https://github.com/splittingred/phpThumbOf/issues/53).  If you give it the phpThumb option `f=jpeg` (image format = jpeg) and you have phpthumbof.hash_thumbnail_names set to No, then—in an attempt to cut off the extension—it trims 5 characters off the end of the filename.  If the extension is only 4 characters (.png) then that means the base file name loses 1 character.  So your image names will all come out as image-.jpeg if you're converting them to jpegs.

There are a few ways to fix it:
- If you look [here](https://github.com/oo12/imageSlim#phpthumbof-notes) you'll find a version of the phpthumbof class which has this bug fixed along with a few other annoying ones.
- In your case, not using the `&convertThreshold` property (set it to empty in default properties) will keep the file names the same, though the images will remain as pngs.
- This weekend I'll update imageSlim so that it doesn't trigger this bug.
- I'm also working on a fork of phpThumbOf with several bug fixes, performance improvements and new features.  I'll try to get that finished this weekend too and package it up if you're interested in trying it.

**Comment by oo12** [comment]
Version [1.0.2](http://modx.com/extras/package/imageslim) is up with a workaround for this problem.  Also take a look at [pThumb](https://github.com/oo12/phpThumbOf), a fork of phpThumbOf which fixes a number of bugs including this one.
