### ISSUE TITLE
Problems with external images

### ISSUE THREAD

**Issue by pepebe** [modxcms/imageSlim#3]
Nice job. Thanks for sharing.

Calling imageSlim on a remote resource:

```
<img src="[[imageSlim? &input=`http://artmetropol.tv/id/00000/0000/000/10/5/vorschau_15.jpg` &remoteImages=`1` &phpthumbof=`w=400`]]" />
```

Has unexpected results:

```
<img src="<p>http://artmetropol.tv/id/00000/0000/000/10/5/vorschau_15.jpg</p>">
```

This happens on modxcloud (latest versions of modx and all relevant extensions). phpthumbof is installed, pThumb isn't.

phpthumb_nohotlink_valid_domains is set to "{http_host},artmetropol.tv"
phpthumb_nohotlink_enabled is set to "No"

Any idea why the image is not processed and how why paragraph tags wrap arround the path if imageSlim fails?

Regards,

pepebe

**Comment by oo12** [comment]
Hi!

**Short answer:**

```
[[imageSlim? &input=`<img src="http://artmetropol.tv/id/00000/0000/000/10/5/vorschau_15.jpg" />` &remoteImages=`1` &phpthumbof=`w=400`]]
```

Although I'm not endorsing actually using it that way.

**Full answer:**
imageSlim expects its input to be a chunk of HTML, like [[*content]] or a rich-text TV, something edited with TinyMCE or CKEditor. It then scans the HTML for &lt;img&gt; tags and where necessary creates a sized-down version of the image and swaps out the src attribute.  You were trying to use it like phpThumbOf, just giving it a file name (a URL in this case).  Since that string didn't contain any &lt;img&gt; tags it didn't find anything to do.
It uses PHP's XML-based DOM parser to do its work and always returns a well formed chunk of XHTML.  Since the string you gave it isn't, it wrapped it in a block-level element, which is &lt;p&gt; by default.  (You'll notice TinyMCE will do the same thing to such a string.)

You could just use phpThumbOf on that image (though the best thing would be to copy it to your site first!):

```
<img src="[[phpthumbof? &input=`http://artmetropol.tv/id/00000/0000/000/10/5/vorschau_15.jpg` &options=`w=400`]]" />
```

However imageSlim's remote image handling is better and fancier: it stores a copy of the original image in its cache directory so any time it has to access it in the future it's much faster.
You've given me a good idea though: to add this same behavior to a future version of pThumb. It would be an improvement on the current remote image handling.

**Comment by pepebe** [comment]
Hi, thanks for your lightning fast reply.

I totally missed the fact that I have to include the whole image tag into the snippet. Reading the documentation a second time I understand where I was wrong. It is there:

```
&input=`[[*content]]`
```

And a bit further down you can also get an idea how it works if you are reading "An example of image sizing".

Still I think it is easy to miss so I think it would be good to elaborate a bit more about snippet usage. Something like this should be sufficient:

```
[[imageSlim? &input=`<img src="http://example.com/text.jpg" />` &remoteImages=`1` &phpthumbof=`w=400`]]
```

Enhancing pThumb would be great.

Question: What is from a performance point of view the better idea?

Using imageSlim on a whole chunk to handle image resizing for all images inside, or invoking phpthumbof/pThumb on each and every image?

**Comment by oo12** [comment]
I'll update the documentation to make this more clear.

As far as performance goes, if you have the images already and know what size they should be beforehand then of course starting out with properly sized images and not relying on the server to do it is the fastest.
pThumb is considerably faster than phpThumbOf when you're sizing multiple images on a page, and I'll have a new version out soon that's faster yet.
imageSlim adds a bit of overhead, but not a lot.  If for some reason you're using remote images it'll still be faster than phpThumbOf.  It's main advantage is when you have an arbitrary chunk of HTML, one which could have, say, a 1000-pixel wide jpeg sized down to 150px, an 800KB png which could be an 80KB jpeg, etc. and you need to give those images some sanity before serving them to every visitor to the page.
