### ISSUE TITLE
&remoteImages=1 will retrieve and inspect small remote images, but doesn't rewrite img.src to point to cached copies

### ISSUE THREAD

**Issue by watou** [modxcms/imageSlim#7]
I have six off-site hotlinked images in my [[*content]] , and I process it like this:

<pre>
[[*content:imageSlim=`remoteImages=1&scale=1&maxWidth=970&debug=1`]]
</pre>

I get a debug dump in an HTML comment:

<pre>
i m a g e S l i m  [1.1.2-pl]
imgSrc:src  scale:1  convertThreshold:none
maxWidth:970  maxHeight:999999  q:
fixAspect:1  phpthumbof:
Remote images:1  Timeout:5  cURL: installed
Retrieved from cache: /foo/site/assets/components/imageslim/cache/www.sample.com-managed-qh1x.jpg
w:120  h:120  realw:120  realh:120  type:jpeg
...
</pre>

but in the following HTML, the original off-site image is present in the img src= attribute, not the locally cached copy.

<pre>
&lt;img src="http://www.sample.com/managed/qh1x.jpg" alt="" width="120" height="120"/&gt;
</pre>

Oughtn't imageSlim rewrite the src attribute to refer to the locally cached copy in this case?

**Comment by oo12** [comment]
Hmm, probably it should, yes.

What it's doing is this:
1. Determines that the src is a remote image.
2. Because remoteImages is set, it downloads the image to its cache.
3. Checks the image's size and finds it doesn't exceed the maxWidth setting (120 px < 970 px)
4. Since the image doesn't need any changes, it leaves the src alone. (Right now imageSlim only changes the src if it's had to modify the image.)

So in this case—a remote image that doesn't need any changes—you end up with a cached image, but the original remote URL in the src.

I changed it so it'll always use the locally cached image.  Give it a try.  Edit the imageSlim snippet in the Manager and copy and paste [this version](https://raw.github.com/oo12/imageSlim/dev/core/components/imageslim/elements/snippets/imageslim.snippet.php) in place of the current one.

I wonder though, are there any instances when this behavior might not be desirable?  For instance, if you're linking to images on a CDN. Though how often would this come up? I'm just thinking whether I should add a setting to control the behavior in the case of no changes needed on a remote image, or whether it's ok to just make it always used the locally cached version (which is exactly the same as the original; only the name is modified somewhat).

**Comment by watou** [comment]
Thanks a lot for the snippet and for working this through.  I envision my client hotlinking images in their rich text content, not just to huge images but also directly off their supplier's or competitor's web sites, and having imageSlim quietly cache them all, resizing some, is a very elegant solution.

While I can't think of a reason to _not_ use the locally cached copy in place of the remote image, someone out there might.  Perhaps the default should be to always use the locally cached copy, but augment the meaning of &remoteImages to encompass what is used as well as is fetched.  Hmmmm.

I will try the new snippet and tell you how it works.  Thanks again.

**Comment by watou** [comment]
Pasted in the new snippet, refreshed that page, and the remote images were replaced by the locally cached versions as expected.  Thanks!  Since this site will eventually be served with a CDN like CloudFlare, there is no particular benefit to using anyone else's CDN copies of images, and lots of reasons not to.

**Comment by oo12** [comment]
Yes I think this new behavior is better in general.  I'll add this change to the next version.

Thanks for pointing it out!

**Comment by watou** [comment]
Many thanks for fixing this, and for this great snippet.
