### ISSUE TITLE
<iframe ...></iframe> is rewritten to <iframe ... />, rendering rest of document unparseable

### ISSUE THREAD

**Issue by watou** [modxcms/imageSlim#8]
In Chrome I embedded a Google Map in my content and rendered the content with imageSlim.  When it rewrote the DOM, it changed `<iframe ...></iframe>` to `<iframe ... />`, which meant the rest of the HTML was unparsed.  If you do a view-source on it, you can see the rest of the document after `<iframe ... />` is not syntax highlighted, because `<iframe ... />` is not valid HTML.  I may have workarounds for this, but if the snippet can prevent this illegal transformation, then no workaround would be needed.  Thanks!

**Comment by oo12** [comment]
Would you send me the original markup for your iframe?  I'll take a look.

By default PHP's XML parser will turn empty tags like that into self-closing tags, which causes exactly the problem you describe.  However since a few versions ago I thought I'd got that fixed for iframe, audio, video and textarea tags, but looks like not in all cases.

I tested iframes and embedded Google Maps (using TinyMCE) and they work fine in my tests, so I'm curious to find out what the difference is.

**Comment by oo12** [comment]
The markup doesn't have to be _exact_; you can change some of the parameters of course to anonymize it.

Does the standard Google Maps embed code work for you?

```
<p>
<iframe src="https://maps.google.com/?ie=UTF8&amp;ll=32.820665,-96.731542&amp;spn=1.204839,1.458435&amp;t=m&amp;z=10&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="425" height="350"></iframe>
<br />
<small><a style="color: #0000ff; text-align: left;" href="https://maps.google.com/?ie=UTF8&amp;ll=32.820665,-96.731542&amp;spn=1.204839,1.458435&amp;t=m&amp;z=10&amp;source=embed">View Larger Map</a></small>
</p>
```

TinyMCE wraps it in a **p** tag, but for me this works fine; **iframe** doesn't get turned into a self-closing tag.

**Comment by watou** [comment]
Here is the output modifier:

```
[[*content:imageSlim=`remoteImages=1&scale=1&maxWidth=970&debug=1`]]
```

Here is the original markup in [[*content]]:

``` html
 <div class="large-6 columns">
  <h4><img width="54" height="54" src="assets/icons/sm/map.png"> Map</h4>
  <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.ie/maps?ie=UTF8&cid=14192984273571253652&q=A+Shop&gl=IE&hl=en&t=m&ll=53.682804,-8.793278&spn=0.006295,0.006295&iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.ie/maps?ie=UTF8&cid=14192984273578255652&q=A+Shop&gl=IE&hl=en&t=m&ll=51.622804,-8.891278&spn=0.006295,0.006295&iwloc=A&amp;source=embed" target="_blank" style="color:#0000FF;text-align:left">View Larger Map</a></small>
 </div>
```

Here is the output:

``` html
 <div class="large-6 columns">
  <h4><img width="54" height="54" src="assets/icons/sm/map.png"/> Map</h4>
  <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.ie/maps?ie=UTF8&amp;cid=14192986173571253652&amp;q=A+Shop&amp;gl=IE&amp;hl=en&amp;t=m&amp;ll=51.582604,-8.871978&amp;spn=0.006295,0.006295&amp;iwloc=A&amp;output=embed"/><br/><small><a href="https://maps.google.ie/maps?ie=UTF8&amp;cid=14192984483571253652&amp;q=A+Shop&amp;gl=IE&amp;hl=en&amp;t=m&amp;ll=51.582804,-8.873578&amp;spn=0.006295,0.006295&amp;iwloc=A&amp;source=embed" target="_blank" style="color:#0000FF;text-align:left">View Larger Map</a></small>
 </div>
```

(Note that github's HTML syntax highlighter is treating <iframe /> as "legal.")

**Comment by watou** [comment]
I've checked more and I now suspect that my HTML was missing a `</div>` somewhere above that fragment, and so your code was not able to be forgiving with a mis-formed DOM tree.  So it's probably not a code problem, but the situation might warrant a warning in the docs that troubleshooting should start with ensuring you have a valid document as input.

**Comment by oo12** [comment]
If you have time, would you mind putting together a test case? Running imageSlim on that bit of the original markup works fine. I've tried putting some unclosed tags before it and even some obviously invalid HTML but it still does ok with the iframe tag..

Are you using a rich-text editor for your [[*content]] in this case, like TinyMCE, CKEditor or Redactor?  My original idea for this extra was that people would run it on markup created by a WYSIWYG editor.  Since those shouldn't let you save any invalid markup, it insures the input is valid to start with, and imageSlim's output shouldn't be changed in any significant way.  (I think those editors use the same parser as imageSlim in fact, so input and output should be very uniform.)

imageSlim uses PHP's [DOMDocument](http://www.php.net/manual/en/class.domdocument.php) to parse the HTML fragment, search for img tags and modify their attributes. Then it writes that DOM tree back out to a string. Internally it deals with everything as XML, and there are a few differences between XML and HTML that can cause problems.  How to close empty tags is the main one since HTML is somewhat inconsistent with this: `<iframe></iframe>`  `<img />` are good but `<iframe />` and `<img></img>` are not.
Also—like with the WYSIWYG editors—the markup it outputs will always be valid (at least as XML :-).  If the input has an unclosed tag, a closing tag will be added in the output.

I wish PHP had real HTML5 support, but for now it's XML only.

**Comment by watou** [comment]
I'm sorry I don't have time to recreate the mess of my hand-edited HTML that tripped up the snippet.  But I'm almost completely certain that it was just a case of garbage-in, garbage-out.  There is no way anyone would expect your snippet to gracefully recover from ill-formed HTML, since your code has to make sense of it in order to change img.src attributes.  In cases where TinyMCE or the like was the last to edit the input, I would doubt that you would see this report often.  Especially if you add a warning to the documentation under troubleshooting about what the snippet might do with ill-formed input.  

While I'm thinking of it, I did have two comments about the docs: 1. Some of your parameters take `1` or `0`, but the column refers to them as `Yes` or `No`.  _You_ know what _you_ mean, but I found it confusing.  2. The core phpthumb system settings for nothotlink control are terribly confusing, so if you could expand that bit of documentation to say more specifically how they should be set, it would decrease the frustration factor in getting remote image fetching to work.

All in all, love your snippet and very grateful you shared it.  I also love the old photo you used to represent it.  Brilliant!

**Comment by oo12** [comment]
Thanks for the kind words about this extra; I'm really glad to that it's useful for you.  I've gotten a lot of use out of MODX and a number of the Extras people have developed so it's nice to be able to contribute something back.

About the documentation:
1. Thanks, I'll update the documentation to make this clearer.  I'd done it that way since if you edit the imageSlim snippet and look in properties—where there's some additional documentation—the boolean items have a choice of  either Yes or No. But if you're setting those same properties in a template or chunk, it's 1/0, so I can see now how that could be confusing.
2. Yes, that nohotlink stuff is rather inscrutable.  I had to look at the actual phpThumb code to figure out how some of those are supposed to work.  Since a few versions ago imageSlim will totally ignore that mess; it only cares about `remoteImages=1` or `remoteImages=0`.  Since it caches any remote images (when that's enabled), they're regular ol' local files by the time phpThumb gets them, or Resizer for that matter.  I'll add a sentence in the documentation about this so people don't waste time on nohotlink settings.

Glad you appreciated the humor of that old photo. I don't know if those fat belt machines enjoyed much popularity outside the States, but funnily enough you can still buy their [modern incarnations](http://www.amazon.com/Sunpentown-UC-633-Belt-Massager/dp/B000P6DOU2/), as dubious as ever :-)

**Comment by watou** [comment]
Thanks very much for the info (but I will skip the belt massager :) ).

**Comment by watou** [comment]
I would like to open the iframe issue again!

Pushing the following HTML through imageSlim causes the first iframe tag to get auto-closed.

``` html
<iframe src="https://maps.google.com/maps/ms?msid=203760324139465242595.00044e5f13b9666b12191&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=53.592505,-8.481445&amp;spn=4.565466,9.338379&amp;z=6&amp;output=embed" frameborder="0" width="425" height="350"></iframe> 
<br /> <small>View <a style="color: #0000ff; text-align: left;" href="https://maps.google.com/maps/ms?msid=203760324139465242595.00044e5f13b9666b12191&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=53.592505,-8.481445&amp;spn=4.565466,9.338379&amp;z=6&amp;source=embed" target="_blank">Irish Surfing Spots</a> in a larger map</small>
<p>So many places to surf in Ireland!</p>

<iframe width="420" height="315" src="//www.youtube.com/embed/BB2Mv85qN_g?rel=0" frameborder="0" allowfullscreen></iframe>
```

Produces this output:

``` html
<iframe src="https://maps.google.com/maps/ms?msid=203760324139465242595.00044e5f13b9666b12191&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=53.592505,-8.481445&amp;spn=4.565466,9.338379&amp;z=6&amp;output=embed" frameborder="0" width="425" height="350"/> 
<br/><small>View <a style="color: #0000ff; text-align: left;" href="https://maps.google.com/maps/ms?msid=203760324139465242595.00044e5f13b9666b12191&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=53.592505,-8.481445&amp;spn=4.565466,9.338379&amp;z=6&amp;source=embed" target="_blank">Irish Surfing Spots</a> in a larger map</small>
<p>So many places to surf in Ireland!</p>

<iframe width="420" height="315" src="//www.youtube.com/embed/BB2Mv85qN_g?rel=0" frameborder="0" allowfullscreen=""></iframe>
```

Unlike earlier, I don't see invalid HTML as a basis for tripping up imageSlim.

Thanks for taking a look.

Regards, watou

**Comment by oo12** [comment]
I'll try to take a look at this tonight!  Is the top one the complete HTML fragment you're running through imageSlim?

One thing you might try as a workaround in the meantime. Try putting something inside the iframe tag so it's not empty, like this:

```
<iframe ...>&nbsp;</iframe>
```

**Comment by watou** [comment]
Yes; the top one is the complete HTML fragment that's being run through imageSlim, and the bottom one is the output.  

And putting `&nbsp;` between the `<iframe>` and `</iframe>` works as a workaround.  Thanks very much for that!

**Comment by oo12** [comment]
Give [this version](https://raw.github.com/oo12/imageSlim/dev/core/components/imageslim/elements/snippets/imageslim.snippet.php) a try; I think it'll fix the problem.  Just copy and paste the code into the imageSlim snippet in the Manager, replacing what's there now.

The old code would work ok with one iframe, but would mess up all but the last one if there's more than one.

Thanks for pointing this out; I might not have realized the problem otherwise!

**Comment by watou** [comment]
Perfect.  I took out the `&nbsp;` between the `<iframe>` and `</iframe>` tags with the new code, and neither got collapsed into `<iframe />` as it did with the old code .  Thank you very much!  And much respect for such quick responses.

**Comment by oo12** [comment]
Great, glad that's got it. I'll put a new version on Extras later this week with this fix and that non-resized remote images change from a couple weeks ago.
